Fixes IPAM result in cni result
k8snetworkplumbingwg/bond-cni pull request #34
Opened 2022-05-06 14:37 UTC by dougbtv

Fixes IPAM result in cni result (which wasn't showing the result.ips object). Also removes duplicated interfaces assignment, just assigns it during initialization of the result object.

Previously, the IP addresses weren't present. This is a requirement for an IPAM CNI plugin, and in turn it was causing issues for other components that rely on having this IPAM result present in a Multus network-status results annotation (especially, Whereabouts IP Reconciliation which was clearing out assigned IP addresses due to this not being present)

2022-05-06 15:17 UTC, maiqueb requested changes
I agree the resulting routes and IPs from the IPAM plugin should be carried back to the result. 

What I a bit unsure of is what should be done with the DNS configuration: IIUC, the IPAM would apply the `bondConf.DNS` , which would be reflected in the CNI result - hence, your code should also delete line 391.

2022-05-06 15:17 UTC, maiqueb commented on bond/bond.go
> +		result.DNS = ipamResult.DNS
this one is being overwritten below, in line 391 by whatever sits at `bondConf.DNS` . 

Which one of those should take precedence ?...

I recommend leaving this attribute out of the fray, focus on the issue at hand (missing IPs / routes), and discuss what should be done regarding DNS in a follow up PR / issue.

2022-05-06 15:43 UTC, maiqueb approved these changes
Thank you.

2022-05-09 08:29 UTC, mmirecki commented
lgtm

2022-05-09 08:29 UTC, mmirecki commented
@killianmuldoon  @Eoghan1232 could you please take a look?

2022-05-09 08:34 UTC, Eoghan1232 approved these changes

2022-05-09 08:35 UTC, merged